#!/bin/bash

export OLLAMA_HOST="[0000:0000:0000:0000:0000:0000:0000:0000]:$PORT"
export OLLAMA_DEBUG=1

# start ollama in the background
echo "Waiting for ollama on $OLLAMA_HOST..."
ollama serve > /dev/null 2>&1 &

# Wait until ollama service is running
until curl -s "http://$OLLAMA_HOST" > /dev/null; do
  echo "Waiting for ollama on $OLLAMA_HOST..."
  sleep 1
done

# run the model
ollama run llama2:7b

echo "Running llama2:7b on $OLLAMA_HOST..."
# Keep the script running
sleep infinity